title: "Jessica Lang"
author: "Jessica Lang"
description: "© Jessica Lang 2024. Powered by Jekyll, inspired by the Contrast theme."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "research.html"}
  - {file: "publications.html"}
  - {file: "teaching.html"}
  - {file: "cv.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jessica.lang@eui.eu"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0002-8462-7534"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
